// dice3d.js — Three.js + Rapier3D dice physics for Dice Rush (v17)
// Item 2a: snapToFace() removed from settle paths — dice keep physics orientation post-roll.
// Item 2b: snapYToNearest90() applied on tween completion — dice parallel in display row.
// Key change from v14: dice values are READ from physics orientation after settling,
// not pre-generated by Math.random(). The physics roll IS the result.
//
// Exports: initDice3D(canvasId) -> Promise<{
//   setDieClass, animateDice, resetAll, setWaiting, showAllValue
// }>
// Note: setDieFace removed — values now come from physics, not written in.

import RAPIER from '@dimforge/rapier3d-compat';

export async function initDice3D(canvasId) {
  await RAPIER.init({});

  const THREE = window.THREE;
  const canvas = document.getElementById(canvasId);
  const container = canvas.parentElement;

  // -- RENDERER -----------------------------------------------------------------
  const W = canvas.width  || 713;
  const H = canvas.height || 606;

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true, canvas });
  renderer.setSize(W, H, false);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;

  const scene = new THREE.Scene();

  // -- CAMERA -------------------------------------------------------------------
  const camera = new THREE.PerspectiveCamera(44, W / H, 0.1, 100);
  camera.position.set(0, 18, 16);
  camera.lookAt(0, -2, -3); // aim lower to push dice toward bottom of canvas

  // -- LIGHTING -----------------------------------------------------------------
  scene.add(new THREE.AmbientLight(0xfff0e0, 0.45));

  const keyLight = new THREE.DirectionalLight(0xfff5e0, 1.4);
  keyLight.position.set(4, 12, 6);
  keyLight.castShadow = true;
  keyLight.shadow.mapSize.set(1024, 1024);
  keyLight.shadow.camera.near = 0.5;
  keyLight.shadow.camera.far  = 60;
  keyLight.shadow.camera.left = keyLight.shadow.camera.bottom = -15;
  keyLight.shadow.camera.right = keyLight.shadow.camera.top  =  15;
  scene.add(keyLight);

  const fillLight = new THREE.DirectionalLight(0xd0e8ff, 0.5);
  fillLight.position.set(-5, 6, -2);
  scene.add(fillLight);

  // -- FLOOR --------------------------------------------------------------------
  const FLOOR_Y = -0.75;

  const floorMesh = new THREE.Mesh(
    new THREE.PlaneGeometry(40, 40),
    new THREE.MeshLambertMaterial({ color: 0x0a2415, transparent: true, opacity: 0.0 })
  );
  floorMesh.rotation.x = -Math.PI / 2;
  floorMesh.position.y = FLOOR_Y;
  floorMesh.receiveShadow = true;
  scene.add(floorMesh);

  const shadowFloor = new THREE.Mesh(
    new THREE.PlaneGeometry(40, 40),
    new THREE.ShadowMaterial({ opacity: 0.50 })
  );
  shadowFloor.rotation.x = -Math.PI / 2;
  shadowFloor.position.y = FLOOR_Y + 0.01;
  shadowFloor.receiveShadow = true;
  scene.add(shadowFloor);

  // -- PIP TEXTURES -------------------------------------------------------------
  const PIP_POSITIONS = {
    1: [[0.5, 0.5]],
    2: [[0.25,0.25],[0.75,0.75]],
    3: [[0.25,0.25],[0.5,0.5],[0.75,0.75]],
    4: [[0.25,0.25],[0.75,0.25],[0.25,0.75],[0.75,0.75]],
    5: [[0.25,0.25],[0.75,0.25],[0.5,0.5],[0.25,0.75],[0.75,0.75]],
    6: [[0.25,0.22],[0.75,0.22],[0.25,0.5],[0.75,0.5],[0.25,0.78],[0.75,0.78]],
  };

  function makeFaceTex(value) {
    const S = 512;
    const cv = document.createElement('canvas');
    cv.width = cv.height = S;
    const ctx = cv.getContext('2d');

    // Define rounded face shape once and clip to it
    const r = 72;
    ctx.beginPath();
    ctx.moveTo(r,0); ctx.lineTo(S-r,0); ctx.quadraticCurveTo(S,0,S,r);
    ctx.lineTo(S,S-r); ctx.quadraticCurveTo(S,S,S-r,S);
    ctx.lineTo(r,S); ctx.quadraticCurveTo(0,S,0,S-r);
    ctx.lineTo(0,r); ctx.quadraticCurveTo(0,0,r,0);
    ctx.closePath();
    ctx.save();
    ctx.clip(); // all drawing below is clipped to this shape

    // Ivory body — warm creamy white with subtle depth
    const g = ctx.createRadialGradient(S*.42, S*.38, 0, S*.5, S*.5, S*.72);
    g.addColorStop(0,   '#fffff0');
    g.addColorStop(0.5, '#f5f0dc');
    g.addColorStop(1,   '#e8e0c8');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, S, S);

    // Subtle ivory grain — very faint warm streaks
    ctx.globalAlpha = 0.04;
    for (let i = 0; i < 20; i++) {
      const x = (S / 20) * i + Math.random() * 4;
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.bezierCurveTo(x + 3, S * 0.4, x - 2, S * 0.7, x + 1, S);
      ctx.strokeStyle = '#c8b890';
      ctx.lineWidth = 1.0;
      ctx.stroke();
    }
    ctx.globalAlpha = 1.0;

    // Soft specular highlight top-left
    const gloss = ctx.createRadialGradient(S * 0.3, S * 0.28, 0, S * 0.3, S * 0.28, S * 0.38);
    gloss.addColorStop(0,   'rgba(255,255,255,0.45)');
    gloss.addColorStop(0.4, 'rgba(255,255,255,0.10)');
    gloss.addColorStop(1,   'rgba(255,255,255,0)');
    ctx.fillStyle = gloss;
    ctx.fillRect(0, 0, S, S);

    ctx.restore(); // end clip

    // Warm edge rim
    ctx.beginPath();
    ctx.moveTo(r,0); ctx.lineTo(S-r,0); ctx.quadraticCurveTo(S,0,S,r);
    ctx.lineTo(S,S-r); ctx.quadraticCurveTo(S,S,S-r,S);
    ctx.lineTo(r,S); ctx.quadraticCurveTo(0,S,0,S-r);
    ctx.lineTo(0,r); ctx.quadraticCurveTo(0,0,r,0);
    ctx.closePath();
    ctx.strokeStyle = 'rgba(180,160,100,0.25)';
    ctx.lineWidth = 5;
    ctx.stroke();

    // Pips
    const pipR = S * 0.092;
    (PIP_POSITIONS[value] || []).forEach(([px, py]) => {
      const cx = px * S, cy = py * S;

      // Pip recess shadow
      ctx.beginPath(); ctx.arc(cx + 2.5, cy + 4, pipR * 1.05, 0, Math.PI * 2);
      ctx.fillStyle = 'rgba(0,0,0,0.85)'; ctx.fill();

      // Pip body
      const pipGrad = ctx.createRadialGradient(
        cx - pipR * 0.2, cy - pipR * 0.25, 0,
        cx, cy, pipR
      );
      if (value === 1) {
        pipGrad.addColorStop(0, '#ff5555');
        pipGrad.addColorStop(1, '#aa1010');
      } else {
        pipGrad.addColorStop(0, '#222222');
        pipGrad.addColorStop(1, '#000000');
      }
      ctx.beginPath(); ctx.arc(cx, cy, pipR, 0, Math.PI * 2);
      ctx.fillStyle = pipGrad; ctx.fill();

      // Pip specular highlight (only on red ace)
      if (value === 1) {
        ctx.beginPath();
        ctx.arc(cx - pipR * 0.28, cy - pipR * 0.32, pipR * 0.38, 0, Math.PI * 2);
        ctx.fillStyle = 'rgba(255,255,255,0.60)'; ctx.fill();
      }
    });

    return new THREE.CanvasTexture(cv);
  }

  const FACE_TEX = {};
  for (let v = 1; v <= 6; v++) FACE_TEX[v] = makeFaceTex(v);

  // -- DIE MATERIALS ------------------------------------------------------------
  // BoxGeometry slot order: +X, -X, +Y, -Y, +Z, -Z
  // FACE_ORDER: slot0=2, slot1=5, slot2=3, slot3=4, slot4=1, slot5=6
  const FACE_ORDER = [2, 5, 3, 4, 1, 6];
  const SCORED_EMISSIVE = new THREE.Color(0x3a2800); // created once, reused
  const NEUTRAL_EMISSIVE = new THREE.Color(0x000000);
  function makeMats() {
    return FACE_ORDER.map(v => {
      const m = new THREE.MeshStandardMaterial({
        map: FACE_TEX[v], roughness: 0.15, metalness: 0.05,
      });
      m.emissive.set(0x000000); // initialise once
      return m;
    });
  }

  // -- FACE DETECTION -----------------------------------------------------------
  // Each face of the die has an outward normal in local space.
  // FACE_NORMALS[value] = the local-space normal of that face.
  // After the die settles, we rotate each normal by the body's quaternion
  // and find which one points most upward (highest dot with UP).
  // That face value is what the die "rolled".
  //
  // Local normals match FACE_ORDER slot assignments:
  //   slot 0 (+X) = value 2  ->  normal ( 1, 0, 0)
  //   slot 1 (-X) = value 5  ->  normal (-1, 0, 0)
  //   slot 2 (+Y) = value 3  ->  normal ( 0, 1, 0)
  //   slot 3 (-Y) = value 4  ->  normal ( 0,-1, 0)
  //   slot 4 (+Z) = value 1  ->  normal ( 0, 0, 1)
  //   slot 5 (-Z) = value 6  ->  normal ( 0, 0,-1)

  const FACE_NORMALS = {
    1: new THREE.Vector3( 0,  0,  1),
    2: new THREE.Vector3( 1,  0,  0),
    3: new THREE.Vector3( 0,  1,  0),
    4: new THREE.Vector3( 0, -1,  0),
    5: new THREE.Vector3(-1,  0,  0),
    6: new THREE.Vector3( 0,  0, -1),
  };
  const UP = new THREE.Vector3(0, 1, 0);

  function readFaceUp(body) {
    // Get the body's current quaternion
    const rot = body.rotation(); // { x, y, z, w }
    const q = new THREE.Quaternion(rot.x, rot.y, rot.z, rot.w);

    let bestValue = 1;
    let bestDot = -Infinity;

    for (let v = 1; v <= 6; v++) {
      // Rotate local face normal into world space
      const worldNormal = FACE_NORMALS[v].clone().applyQuaternion(q);
      const dot = worldNormal.dot(UP);
      if (dot > bestDot) {
        bestDot = dot;
        bestValue = v;
      }
    }
    return bestValue;
  }

  // -- FACE SNAP (display) ------------------------------------------------------
  // After reading the value from physics, we snap the mesh to a clean camera-facing
  // orientation that shows the correct face. Uses the same verified quaternion approach.
  const CAM_DIR = new THREE.Vector3(0, 18, 16).normalize();

  function makeSnapQuat(faceNormal) {
    const q = new THREE.Quaternion();
    q.setFromUnitVectors(faceNormal, CAM_DIR);
    return q;
  }

  const SNAP_QUAT = {
    1: makeSnapQuat(new THREE.Vector3( 0,  0,  1)),
    2: makeSnapQuat(new THREE.Vector3( 1,  0,  0)),
    3: makeSnapQuat(new THREE.Vector3( 0,  1,  0)),
    4: makeSnapQuat(new THREE.Vector3( 0, -1,  0)),
    5: makeSnapQuat(new THREE.Vector3(-1,  0,  0)),
    6: makeSnapQuat(new THREE.Vector3( 0,  0, -1)),
  };

  function snapToFace(mesh, value) {
    mesh.quaternion.copy(SNAP_QUAT[value] || SNAP_QUAT[1]);
  }

  // -- RAPIER WORLD -------------------------------------------------------------
  const world = new RAPIER.World({ x: 0, y: -60, z: 0 });

  function addWall(px, py, pz, hx, hy, hz) {
    const body = world.createRigidBody(
      RAPIER.RigidBodyDesc.fixed().setTranslation(px, py, pz)
    );
    world.createCollider(
      RAPIER.ColliderDesc.cuboid(hx, hy, hz).setFriction(0.4).setRestitution(0.35),
      body
    );
  }

  // -- PIT WALLS ----------------------------------------------------------------
  const PIT_HALF_W = 7.5;
  const PIT_HALF_D = 5.0;
  const WALL_H = 6, WALL_T = 0.25;

  addWall(0, FLOOR_Y - WALL_T,           0,  PIT_HALF_W, WALL_T,  PIT_HALF_D); // floor
  addWall(0, WALL_H/2, -(PIT_HALF_D + WALL_T), PIT_HALF_W, WALL_H, WALL_T);    // far
  addWall(0, WALL_H/2,  (PIT_HALF_D + WALL_T), PIT_HALF_W, WALL_H, WALL_T);    // near
  addWall(-(PIT_HALF_W + WALL_T), WALL_H/2, 0, WALL_T, WALL_H, PIT_HALF_D);    // left
  addWall( (PIT_HALF_W + WALL_T), WALL_H/2, 0, WALL_T, WALL_H, PIT_HALF_D);    // right

  // Visible pit walls removed — physics colliders above handle containment.

  // -- DICE ---------------------------------------------------------------------
  const NUM_DICE  = 5;
  const dieSize   = 1.030;  // 15% + 5% smaller
  const dieHalf   = dieSize / 2;
  const dice      = [];
  const bodies    = [];
  const diceState = []; // { value, scored, bust }
  const settled   = [];

  const REST_POS = [
    {x:-2.2, z:-1.6}, {x: 2.0, z:-1.8}, {x:-0.2, z: 0.4},
    {x: 2.2, z: 1.8}, {x:-2.0, z: 2.0},
  ];

  for (let i = 0; i < NUM_DICE; i++) {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(dieSize, dieSize, dieSize),
      makeMats()
    );
    mesh.castShadow = true;
    mesh.position.set(REST_POS[i].x, FLOOR_Y + dieHalf, REST_POS[i].z);
    scene.add(mesh);
    dice.push(mesh);
    diceState.push({ value: 6, scored: false, bust: false });
    settled.push(true);

    const body = world.createRigidBody(
      RAPIER.RigidBodyDesc.dynamic()
        .setTranslation(REST_POS[i].x, FLOOR_Y + dieHalf, REST_POS[i].z)
        .setLinearDamping(0.08)
        .setAngularDamping(0.08)
        .setSleeping(true)
    );
    world.createCollider(
      RAPIER.ColliderDesc.cuboid(dieHalf, dieHalf, dieHalf)
        .setFriction(0.4)
        .setRestitution(0.35)
        .setDensity(1.15),  // 15% heavier
      body
    );
    bodies.push(body);
  }

  // -- APPEARANCE ---------------------------------------------------------------
  function applyAppearance(mesh, state) {
    mesh.material.forEach(m => {
      // Use .copy() not assignment — avoids triggering needsUpdate
      m.emissive.copy(state.scored ? SCORED_EMISSIVE : NEUTRAL_EMISSIVE);
      m.emissiveIntensity = state.scored ? 0.6 : 0;
      m.roughness         = state.bust ? 0.6 : state.scored ? 0.2 : 0.15;
    });
    mesh.scale.setScalar(state.scored ? 1.06 : state.bust ? 0.85 : 1.0);
  }

  // -- Y-SNAP HELPER -------------------------------------------------------------
  // Item 2b: after the present tween completes, snap each die's Y rotation to the
  // nearest 90° so all dice in the row are parallel (sides face sides, not edges).
  // Only the Y axis is touched — the top face (which determines the value) is preserved.
  function snapYToNearest90(mesh) {
    // Decompose current quaternion into Euler, round Y to nearest 90°, recompose.
    const euler = new THREE.Euler().setFromQuaternion(mesh.quaternion, 'YXZ');
    euler.y = Math.round(euler.y / (Math.PI / 2)) * (Math.PI / 2);
    mesh.quaternion.setFromEuler(euler);
  }

  // -- PRESENT SLOTS ------------------------------------------------------------
  // After settling, all dice glide to a clean centred display row.
  // Scored (locked) dice: near edge, gold glow.
  // Active dice: centre of pit, neutral.
  const PRESENT_SPACING = dieSize + 0.3;
  const PRESENT_Y       = FLOOR_Y + dieHalf;
  const SCORED_Z        = PIT_HALF_D * 0.95;  // pushed further to near edge
  const ACTIVE_Z        = -1.5;               // pushed further to far side

  const presentTweens = dice.map(() => ({ active: false, tx: 0, tz: 0, progress: 0 }));

  function presentDice(scoredIndices) {
    const scored = (scoredIndices || []).slice().sort((a, b) => a - b);
    const active = [0,1,2,3,4].filter(i => scored.indexOf(i) === -1);

    const scoredTotalW = (scored.length - 1) * PRESENT_SPACING;
    scored.forEach((dieIdx, si) => {
      const tx = scored.length > 1 ? -scoredTotalW / 2 + si * PRESENT_SPACING : 0;
      presentTweens[dieIdx] = { active: true, tx, tz: SCORED_Z, progress: 0 };
    });

    const activeTotalW = (active.length - 1) * PRESENT_SPACING;
    active.forEach((dieIdx, ai) => {
      const tx = active.length > 1 ? -activeTotalW / 2 + ai * PRESENT_SPACING : 0;
      presentTweens[dieIdx] = { active: true, tx, tz: ACTIVE_Z, progress: 0 };
    });
  }

  // -- LAUNCH POSITIONS ---------------------------------------------------------
  const LAUNCH_X = [-3.0, -1.5, 0, 1.5, 3.0];

  // -- RENDER LOOP --------------------------------------------------------------
  let lastTime = null;

  function animate(ts) {
    requestAnimationFrame(animate);
    if (lastTime === null) { lastTime = ts; return; }
    const dt = Math.min((ts - lastTime) / 1000, 0.05);
    lastTime = ts;

    world.step();

    dice.forEach((mesh, i) => {
      // Present tween: glide die to display slot
      const tween = presentTweens[i];
      if (tween.active) {
        tween.progress = Math.min(tween.progress + dt * 4.0, 1);
        const ease = 1 - Math.pow(1 - tween.progress, 3);
        mesh.position.x += (tween.tx - mesh.position.x) * ease * 0.2;
        mesh.position.z += (tween.tz - mesh.position.z) * ease * 0.2;
        mesh.position.y  = PRESENT_Y;
        if (tween.progress >= 1) {
          tween.active    = false;
          mesh.position.x = tween.tx;
          mesh.position.z = tween.tz;
          mesh.position.y = PRESENT_Y;
          bodies[i].setTranslation({ x: tween.tx, y: PRESENT_Y, z: tween.tz }, true);
          bodies[i].sleep();
          // Item 2b: snap Y to nearest 90° so dice in row are parallel
          snapYToNearest90(mesh);
        }
        return;
      }

      const b          = bodies[i];
      const isSleeping = b.isSleeping();
      if (!isSleeping) settled[i] = false;

      if (!settled[i]) {
        // Sync mesh to physics while rolling
        const t = b.translation();
        const r = b.rotation();
        mesh.position.set(t.x, t.y, t.z);
        mesh.quaternion.set(r.x, r.y, r.z, r.w);

        // Clamp to pit bounds
        mesh.position.x = Math.max(-(PIT_HALF_W - dieHalf), Math.min(PIT_HALF_W - dieHalf, mesh.position.x));
        mesh.position.z = Math.max(-(PIT_HALF_D - dieHalf), Math.min(PIT_HALF_D - dieHalf, mesh.position.z));
        if (mesh.position.y < FLOOR_Y + dieHalf * 0.5) mesh.position.y = FLOOR_Y + dieHalf;

        // When physics sleeps naturally, read face from orientation
        if (isSleeping) {
          settled[i] = true;
          diceState[i].value = readFaceUp(b);
          mesh.position.y = FLOOR_Y + dieHalf;
          // Item 2a: no snapToFace — keep the physics orientation as-is
        }
      }
    });

    renderer.render(scene, camera);
  }
  requestAnimationFrame(animate);

  // -- RESIZE -------------------------------------------------------------------
  new ResizeObserver(() => {
    const w = container.clientWidth  || 713;
    const h = container.clientHeight || 606;
    renderer.setSize(w, h, false);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
  }).observe(container);

  // -- SETTLE POLLER ------------------------------------------------------------
  // Polls until all active dice (not in lockedIndices) have settled naturally.
  // Returns a Promise that resolves with the rolled values array [d0..d4].
  // Falls back after maxMs to force-settle any stragglers.
  function waitForSettle(lockedIndices, maxMs) {
    const locked = lockedIndices || [];
    const active = [0,1,2,3,4].filter(i => locked.indexOf(i) === -1);
    const start  = performance.now();
    const POLL_INTERVAL = 80; // ms between checks

    return new Promise(resolve => {
      function check() {
        const allSettled = active.every(i => settled[i]);
        const timedOut   = (performance.now() - start) >= maxMs;

        if (allSettled || timedOut) {
          // Force-settle any stragglers (timeout case)
          active.forEach(i => {
            if (!settled[i]) {
              const body = bodies[i];
              body.setLinvel({ x: 0, y: 0, z: 0 }, true);
              body.setAngvel({ x: 0, y: 0, z: 0 }, true);
              body.sleep();
              settled[i] = true;
              diceState[i].value = readFaceUp(body); // read even on timeout
              dice[i].position.y = FLOOR_Y + dieHalf;
              // Item 2a: no snapToFace on force-settle either
            }
          });

          // Return full 5-die value array (locked dice keep their existing values)
          resolve(diceState.map(s => s.value));
        } else {
          setTimeout(check, POLL_INTERVAL);
        }
      }
      setTimeout(check, POLL_INTERVAL);
    });
  }

  // -- PUBLIC API ---------------------------------------------------------------

  // setDieClass: called by main.js after scoring to apply scored/bust appearance.
  // Values are no longer written from outside — they come from physics.
  function setDieClass(index, cls) {
    diceState[index].scored = cls === 'scored';
    diceState[index].bust   = cls === 'bust';
    applyAppearance(dice[index], diceState[index]);
  }

  // animateDice: launches active dice, waits for them to settle naturally,
  // reads their values from physics orientation, then calls back with those values
  // so game logic (processRoll) can score them.
  //
  // Signature change from v14:
  //   callback(rolledValues) — called with array of 5 values after dice settle.
  //   main.js must pass these into processRoll instead of generating them internally.
  function animateDice(lockedIndices, callback) {
    const locked = lockedIndices || [];
    const MAX_SETTLE_MS = 4000; // fallback timeout

    dice.forEach((mesh, i) => {
      if (locked.indexOf(i) !== -1) return;

      const body = bodies[i];
      body.wakeUp();
      settled[i] = false;
      presentTweens[i].active = false;

      body.setTranslation({
        x: LAUNCH_X[i] * 0.6 + (Math.random() - 0.5) * 0.6,
        y: FLOOR_Y + 5.0,
        z: PIT_HALF_D * 0.95,  // launch from near edge where scored dice sit
      }, true);
      body.setLinvel({ x: 0, y: 0, z: 0 }, true);
      body.setAngvel({ x: 0, y: 0, z: 0 }, true);
      body.setLinvel({
        x: (Math.random() - 0.5) * 6.25,
        y:  9.4 + Math.random() * 6.25,
        z: -(25 + Math.random() * 7.8),
      }, true);
      body.setAngvel({
        x: (Math.random() - 0.5) * 62.5,
        y: (Math.random() - 0.5) * 62.5,
        z: (Math.random() - 0.5) * 62.5,
      }, true);

      diceState[i].scored = false;
      diceState[i].bust   = false;
      applyAppearance(mesh, diceState[i]);
    });

    // Wait for physics to settle, read values, then call back
    waitForSettle(locked, MAX_SETTLE_MS).then(values => {
      // callback receives the full 5-die values array read from physics
      callback(values);

      // Present all dice in display row
      const allScored = [0,1,2,3,4].filter(i => diceState[i].scored);
      presentDice(allScored);
    });
  }

  function resetAll() {
    dice.forEach((mesh, i) => {
      diceState[i] = { value: 6, scored: false, bust: false };
      presentTweens[i].active = false;
      settled[i] = true;
      const body = bodies[i];
      body.setLinvel({ x: 0, y: 0, z: 0 }, true);
      body.setAngvel({ x: 0, y: 0, z: 0 }, true);
      body.setTranslation({ x: REST_POS[i].x, y: FLOOR_Y + dieHalf, z: REST_POS[i].z }, true);
      body.sleep();
      mesh.position.set(REST_POS[i].x, FLOOR_Y + dieHalf, REST_POS[i].z);
      mesh.scale.setScalar(1.0);
      snapToFace(mesh, 6);
      applyAppearance(mesh, diceState[i]);
    });
  }

  function setWaiting(isWaiting) {
    dice.forEach(mesh => {
      mesh.material.forEach(m => {
        m.opacity     = isWaiting ? 0.25 : 1.0;
        m.transparent = isWaiting;
      });
    });
  }

  // -- CALIBRATION (remove before release) --------------------------------------
  function showAllValue(v) {
    dice.forEach((mesh, i) => {
      diceState[i].value = v;
      bodies[i].setLinvel({ x: 0, y: 0, z: 0 }, true);
      bodies[i].setAngvel({ x: 0, y: 0, z: 0 }, true);
      bodies[i].sleep();
      settled[i] = true;
      presentTweens[i].active = false;
      mesh.position.set(REST_POS[i].x, FLOOR_Y + dieHalf, REST_POS[i].z);
      snapToFace(mesh, v);
      applyAppearance(mesh, diceState[i]);
    });
  }

  return { setDieClass, animateDice, resetAll, setWaiting, showAllValue };
}
